#!/usr/bin/env node
/**
 * Token build: DTCG JSON -> CSS custom properties + TypeScript constants.
 *
 * Source of truth is the JSON under `tokens/`. Everything in `build/` is generated and
 * gitignored — never hand-edit it, and never import from it in a way that assumes a token
 * exists. Edit the JSON and rebuild.
 *
 * The CSS custom-property prefix comes from /ds.config.json. Rebranding is an explicit migration;
 * this compiler never carries a second hard-coded identity.
 *
 * Runs green on an empty token directory. That remains deliberate: an unmeasured downstream
 * system may legitimately start empty even though this reference repository now has tokens.
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync, readdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve, join } from 'node:path';
import StyleDictionary from 'style-dictionary';
import { propertyFormatNames } from 'style-dictionary/enums';
import { fileHeader, formattedVariables } from 'style-dictionary/utils';
import { composeHexOpacity } from './paint.mjs';

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, '../..');

const dsConfig = JSON.parse(readFileSync(join(repoRoot, 'ds.config.json'), 'utf8'));
const PREFIX = dsConfig.tokenPrefix;

/**
 * Style Dictionary globs with forward slashes only. On Windows `path.join` yields backslashes,
 * which match nothing — the build then reports "built 0 tokens" and writes no files while
 * exiting 0, so it looks like an empty token set rather than a broken glob. Normalise.
 */
const posix = (p) => p.split('\\').join('/');

const SOURCE = posix(join(here, 'tokens/**/*.json'));
const BUILD = posix(join(here, 'build'));

/**
 * Sort with a fixed code-point comparator, never localeCompare.
 * A locale-dependent sort makes generated output machine-dependent, which turns every CI
 * regeneration into a phantom diff. The reference system this is drawn from shipped exactly
 * that bug once.
 */
const byCodePoint = (a, b) => (a < b ? -1 : a > b ? 1 : 0);

/**
 * A JS constants file, so tokens and derived paints are reachable from script without parsing CSS.
 *
 * Keyed by the **CSS custom-property name** — the same string the stylesheet uses — because the
 * thing callers actually want is `var(...)`, and a second casing convention (DsColorBrandPrimary)
 * would be a second name for one token, which is the duplication this whole repo is built to
 * avoid. Emits plain JS; the types live in the generated .d.ts beside it.
 */
StyleDictionary.registerFormat({
  name: 'ds/js-constants',
  format: ({ dictionary, file }) => {
    const body = outputEntries(dictionary)
      .map(([name, value]) => `  ${JSON.stringify(name)}: ${JSON.stringify(value)},`)
      .join('\n');
    return [
      `// ${file.destination} — GENERATED by packages/tokens/style-dictionary.config.mjs.`,
      `// Do not edit. Change the DTCG JSON under packages/tokens/tokens/ and run \`pnpm build:tokens\`.`,
      ``,
      `export const tokens = {`,
      body,
      `};`,
      ``,
    ].join('\n');
  },
});

/** `[["--juro-color-brand-primary", "#5146e6"], ...]`, sorted deterministically. */
function sourceTokenEntries(dictionary) {
  return [...dictionary.allTokens]
    .map((t) => [`--${t.name}`, String(t.$value ?? t.value)])
    .sort((a, b) => byCodePoint(a[0], b[0]));
}

/** Semantic `opacity.<role>` owns a generated web paint paired with `color.<role>`. */
function paintEntries(dictionary) {
  const byPath = new Map(dictionary.allTokens.map((token) => [token.path.join('.'), token]));
  return dictionary.allTokens
    .filter((token) => {
      const [group, step] = token.path;
      return group === 'opacity' && token.path.length > 2 && !/^\d+$/.test(step);
    })
    .map((opacity) => {
      const suffix = opacity.path.slice(1);
      const colorPath = ['color', ...suffix].join('.');
      const color = byPath.get(colorPath);
      if (!color) throw new Error(`${opacity.path.join('.')} has no paired ${colorPath}.`);

      let value;
      try {
        value = composeHexOpacity(color.$value ?? color.value, opacity.$value ?? opacity.value);
      } catch (error) {
        throw new Error(
          `Cannot compile ${colorPath} + ${opacity.path.join('.')}: ${error.message}`,
        );
      }
      return [`--${PREFIX}-paint-${suffix.join('-')}`, value];
    })
    .sort((a, b) => byCodePoint(a[0], b[0]));
}

function outputEntries(dictionary) {
  return [...sourceTokenEntries(dictionary), ...paintEntries(dictionary)].sort((a, b) =>
    byCodePoint(a[0], b[0]),
  );
}

StyleDictionary.registerFormat({
  name: 'ds/css-variables',
  format: async ({ dictionary, file, options = {} }) => {
    const header = await fileHeader({ file, options });
    const variables = formattedVariables({
      format: propertyFormatNames.css,
      dictionary,
      outputReferences: options.outputReferences,
      usesDtcg: true,
      formatting: { indentation: '  ' },
    });
    const paints = paintEntries(dictionary)
      .map(([name, value]) => `  ${name}: ${value};`)
      .join('\n');
    return `${header}:root {\n${variables}${paints ? `\n${paints}` : ''}\n}\n`;
  },
});

const config = {
  source: [SOURCE],
  // DTCG ($value / $type) is the authoring format. See tokens/README.md.
  usesDtcg: true,
  log: { verbosity: 'default', warnings: 'warn' },
  platforms: {
    css: {
      transformGroup: 'css',
      prefix: PREFIX,
      buildPath: `${BUILD}/css/`,
      options: { usesDtcg: true },
      files: [
        {
          destination: 'variables.css',
          format: 'ds/css-variables',
          options: { outputReferences: true },
        },
      ],
    },
    ts: {
      // `css`, not `js` — the keys are CSS custom-property names, so they must go through the
      // same name transform the stylesheet does. See ds/js-constants above.
      transformGroup: 'css',
      prefix: PREFIX,
      buildPath: `${BUILD}/ts/`,
      options: { usesDtcg: true },
      files: [{ destination: 'index.js', format: 'ds/js-constants' }],
    },
  },
};

/** Emit the shape an empty system still has to provide, so consumers never import nothing. */
function writeEmptyOutputs(reason) {
  mkdirSync(join(BUILD, 'css'), { recursive: true });
  mkdirSync(join(BUILD, 'ts'), { recursive: true });
  writeFileSync(
    join(BUILD, 'css/variables.css'),
    `/* GENERATED — no tokens yet.\n   ${reason}\n   Add DTCG JSON under packages/tokens/tokens/ and run \`pnpm build:tokens\`. */\n:root {\n}\n`,
  );
  writeFileSync(
    join(BUILD, 'ts/index.js'),
    `// GENERATED — no tokens yet. ${reason}\nexport const tokens = {};\n`,
  );
}

/** The .d.ts beside index.js. Names each property so a typo is a type error, not silent undefined. */
function writeTypes(names) {
  const lines = [
    `// GENERATED by packages/tokens/style-dictionary.config.mjs. Do not edit.`,
    `export declare const tokens: {`,
    ...names.map((n) => `  ${JSON.stringify(n)}: string;`),
    `};`,
    `export type TokenName = keyof typeof tokens;`,
    ``,
  ];
  writeFileSync(join(BUILD, 'ts/index.d.ts'), lines.join('\n'));
}

/** A formatter regression must not silently omit the public properties the ADR promises. */
function verifyPaintOutputs(paints) {
  const css = readFileSync(join(BUILD, 'css/variables.css'), 'utf8');
  const js = readFileSync(join(BUILD, 'ts/index.js'), 'utf8');
  const types = readFileSync(join(BUILD, 'ts/index.d.ts'), 'utf8');
  for (const [name, value] of paints) {
    if (!css.includes(`${name}: ${value};`)) {
      throw new Error(`Generated CSS is missing derived paint ${name}.`);
    }
    if (!js.includes(`${JSON.stringify(name)}: ${JSON.stringify(value)}`)) {
      throw new Error(`Generated JavaScript is missing derived paint ${name}.`);
    }
    if (!types.includes(`${JSON.stringify(name)}: string;`)) {
      throw new Error(`Generated declarations are missing derived paint ${name}.`);
    }
  }
}

async function build() {
  const tokensDir = join(here, 'tokens');
  const hasSource =
    existsSync(tokensDir) && readdirSync(tokensDir).some((f) => f.endsWith('.json'));

  if (!hasSource) {
    writeEmptyOutputs('No token files found under packages/tokens/tokens/.');
    writeTypes([]);
    console.log('tokens: no source files — emitted empty CSS + TS. This is a valid state.');
    return;
  }

  const sd = new StyleDictionary(config);
  await sd.buildAllPlatforms();

  const dict = await sd.getPlatformTokens('ts');
  const sourceCount = dict.allTokens.length;
  const paints = paintEntries(dict);
  const names = outputEntries(dict).map(([name]) => name);

  // Style Dictionary skips a file with zero tokens rather than writing an empty one, so a
  // token directory holding only non-token JSON would leave stale or missing output. Cover it.
  if (sourceCount === 0) {
    writeEmptyOutputs('Token files were found, but none contained a token.');
    writeTypes([]);
    console.log('tokens: source files present but no tokens in them — emitted empty CSS + TS.');
    return;
  }

  writeTypes(names);
  verifyPaintOutputs(paints);
  console.log(`tokens: built ${sourceCount} token(s) + ${paints.length} derived paint(s).`);
}

build().catch((err) => {
  // A build step that throws must reach a non-zero exit, or CI stays green on a failed build.
  console.error(err);
  process.exit(1);
});
