import { existsSync, readFileSync, readdirSync, rmdirSync, rmSync, writeFileSync } from 'node:fs';
import { join, relative, resolve } from 'node:path';

// Skip by denylist, never by an allowlist of dot-directories. An earlier allowlist covered known
// tool directories but silently missed apps/storybook/.storybook, leaving imports under the old
// package scope. With a denylist, new directories are renamed by default.
export const SKIP_DIRS = new Set([
  'node_modules',
  'browser-generated',
  '.git',
  'dist',
  'build',
  '.vite',
  '.turbo',
  'storybook-static',
  'coverage',
]);

// The codemod files contain the rules themselves; rewriting them would corrupt the running tool
// and make its result depend on traversal order. The lockfile is regenerated by `pnpm install`
// after package manifests move, rather than being edited as text.
export const SKIP_FILES = new Set([
  'scripts/init-ds.mjs',
  'scripts/init-ds-lib.mjs',
  'pnpm-lock.yaml',
]);

// Missing a source extension creates exactly the silent half-rename this tool prevents. `.vue`
// was added with the Vue backend after generated SFCs retained old imports and data attributes.
// Adding a backend means reviewing this list.
export const EXTENSIONS = new Set([
  '.ts',
  '.tsx',
  '.js',
  '.jsx',
  '.mjs',
  '.cjs',
  '.json',
  '.css',
  '.md',
  '.html',
  '.vue',
  '.yaml',
  '.yml',
]);

const NAME_PATTERN = /^[a-z][a-z0-9]*$/;

export function validName(name) {
  return typeof name === 'string' && NAME_PATTERN.test(name);
}

export function identityProblems(config) {
  if (!config || typeof config !== 'object' || Array.isArray(config)) {
    return ['ds.config.json must contain an object.'];
  }

  const problems = [];
  if (!validName(config.name)) {
    problems.push(
      `name must be lowercase letters and digits, starting with a letter; received ${JSON.stringify(config.name)}.`,
    );
    return problems;
  }

  for (const [field, expected] of [
    ['scope', `@${config.name}`],
    ['tokenPrefix', config.name],
    ['dataPrefix', config.name],
  ]) {
    if (config[field] !== expected) {
      problems.push(
        `${field} is ${JSON.stringify(config[field])}; expected ${JSON.stringify(expected)}.`,
      );
    }
  }
  return problems;
}

export function componentTags(root) {
  // Contracts are the authoritative component inventory. Deriving tags from them avoids a broad
  // prefix rule that would also rename agent-tooling names such as `ds-decide`.
  const dir = join(root, 'packages/contracts/components');
  if (!existsSync(dir)) return [];
  return readdirSync(dir, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase())
    .sort();
}

export function buildRules(from, name, tags) {
  return [
    [new RegExp(`data-${from}-`, 'g'), `data-${name}-`],
    [new RegExp(`@${from}/`, 'g'), `@${name}/`],
    [new RegExp(`--${from}-`, 'g'), `--${name}-`],
    // `String.raw` is required: in a normal template literal `\b` becomes a backspace character,
    // so the rule silently matches nothing. Prefix+capital identifiers are reserved for Angular
    // selectors and other generated identifiers in this family.
    [new RegExp(String.raw`\b${from}(?=[A-Z])`, 'g'), name],
    // A component tag also namespaces related identifiers such as ds-button-spin. Only reject a
    // match when the old prefix is itself the suffix of another word or hyphenated namespace.
    ...(tags.length
      ? [[new RegExp(String.raw`(?<![\w-])${from}-(?=(?:${tags.join('|')})\b)`, 'g'), `${name}-`]]
      : []),
  ];
}

export function applyRules(text, rules) {
  let result = text;
  for (const [pattern, replacement] of rules) result = result.replace(pattern, replacement);
  return result;
}

function countMatches(text, pattern) {
  return [...text.matchAll(new RegExp(pattern.source, pattern.flags))].length;
}

export function* walk(root, dir = root) {
  for (const entry of readdirSync(dir, { withFileTypes: true }).sort((a, b) =>
    a.name < b.name ? -1 : 1,
  )) {
    if (SKIP_DIRS.has(entry.name)) continue;

    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      // A nested repository or worktree belongs to another checkout. Its .git may be a directory
      // or a gitdir file; either form is a hard traversal boundary.
      if (existsSync(join(full, '.git'))) continue;
      yield* walk(root, full);
    } else if (EXTENSIONS.has(entry.name.slice(entry.name.lastIndexOf('.')))) {
      yield full;
    }
  }
}

export function planRenames(root, rules) {
  const changed = [];
  for (const file of walk(root)) {
    const relativePath = relative(root, file).split('\\').join('/');
    if (SKIP_FILES.has(relativePath)) continue;

    const before = readFileSync(file, 'utf8');
    const after = applyRules(before, rules);
    if (after !== before) {
      changed.push({
        file: relativePath,
        path: file,
        before,
        after,
        hits: rules.reduce((total, [pattern]) => total + countMatches(before, pattern), 0),
      });
    }
  }
  return changed;
}

export function writeRenamePlan(changed) {
  for (const change of changed) writeFileSync(change.path, change.after);
}

export function renameTree(root, rules, { dry = false } = {}) {
  const changed = planRenames(root, rules);
  if (!dry) writeRenamePlan(changed);
  return changed;
}

export function snapshotPaths(paths) {
  const snapshot = new Map();
  for (const path of new Set(paths.map((path) => resolve(path)))) {
    const existed = existsSync(path);
    snapshot.set(path, {
      existed,
      contents: existed ? readFileSync(path) : null,
    });
  }
  return snapshot;
}

export function restoreSnapshot(snapshot) {
  const failures = [];
  for (const [path, state] of snapshot) {
    try {
      if (state.existed) writeFileSync(path, state.contents);
      else rmSync(path, { force: true });
    } catch (error) {
      failures.push(`${path}: ${error instanceof Error ? error.message : String(error)}`);
    }
  }
  return failures;
}

export function removeCreatedDirectories(directories) {
  const failures = [];
  for (const directory of [...directories].reverse()) {
    if (directory.existed || !existsSync(directory.path)) continue;
    try {
      rmdirSync(directory.path);
    } catch (error) {
      failures.push(`${directory.path}: ${error instanceof Error ? error.message : String(error)}`);
    }
  }
  return failures;
}
